### ISSUE TITLE
Allow to serve dist folder, e.g. ui5 serve --dist

### ISSUE THREAD

**Issue by petermuessig** [UI5/cli#300]
## Expected Behavior
I would like to be able to serve the dist resources via the `ui5 serve` command, e.g. via a dedicated command line options like `--dist`.

## Current Behavior
As of today, the best workaround is to create a separate ui5.yaml file (e.g. ui5-dist.yaml) which shifts the project resources configuration for webapp to the dist folder:

```
specVersion: ‘1.0’
metadata:
 name: openui5-sample-app
type: application
resources:
 configuration:
   paths:
     webapp: dist
```

Now the project can be served from the dist folder via `ui5 serve --config ui5-dist.yaml`.
